version: "3.9"

services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5433:5432"


  django:
    build: 
      context: ./docker/django
      dockerfile: Dockerfile
    volumes:
      - ./src/app:/code/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    tty: true


  front:
    build:
      context: ./docker/nuxt
      dockerfile: Dockerfile
    volumes: 
      - ./src/frontend:/code
    ports: 
      - "3000:3000"
    depends_on:
      - django
    tty: true