# Generated by Django 3.2.8 on 2022-04-21 05:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store', to='shirotengu.store')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='開始時刻')),
                ('end_time', models.DateTimeField(verbose_name='終了時刻')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='店名', to='shirotengu.store')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='勤務者', to='shirotengu.user')),
            ],
        ),
    ]
